#!/bin/sh
user_input=$(\
  dialog --title "Selet time to shutdown" \
         --inputbox "Enter the time:" 8 40 \
  3>&1 1>&2 2>&3 3>&- \
)

touch /tmp/timer
echo $user_input >> /tmp/timer

{
	if sleep "$user_input"; then
		mpv --audio-display=no --volume=75 "/mnt/data/Audio/miscellaneous/alarm-clock-beep.mp3"
		sleep 5s
		shutdown now
	else
		echo "pcStart Failed!"
		rm /tmp/timer
	fi
} &

pgrep i3 || startx "~/.xinitrc"
